### PR TITLE
Filled in Instruction 1.3 & 1.4

### PR DESCRIPTION
**Pull request by jjjjesse**
Everything seems to run, collects tweets.

Kept the "#INSERT YOUR CODE"s for clarity for now

### CODE REVIEW

**Comment by willem-h** [comment]
I like keeping the `#INSERT YOUR CODE` comments. They help us to keep communication high and understand where each other has edited the document. This notebook form makes it a little tricky to see what has changed so anything that can help us see that is a win 👍

**Comment by jjjjesse** [comment]
Yeah, I reckon we clear them out at the very end

**Comment by willem-h** [comment]
Do you reckon we'd need to? I left them in for assignment 1. They might even help those who are marking it?

**Comment by jjjjesse** [comment]
Oh maybe, I didn't consider that.

**Review by willem-h — APPROVED** [review]
Thanks for storming ahead on this Jesse 👌

**Comment by jjjjesse** [comment]
Nah, I enjoy it. As long as you guys don't mind of course

**Pull request merged**
