### PR TITLE
Ignore the checkpoints folder

### PR DESCRIPTION
**Pull request by afestein**
This folder contains files which are auto-generated by Jupyter, which are useful for local save
checkpoints, but we probably don't need to commit these files.

### CODE REVIEW

**Comment by afestein** [comment]
👀 please @jjjjesse @willem-h

**Comment by jjjjesse** [comment]
Looks good.
Are we having one person approve to merge or 2 btw?

**Comment by afestein** [comment]
I reckon just change the repo settings so that we need one approval to merge?

**Comment by jjjjesse** [comment]
I meant verbal approval specifically

**Pull request merged**
