### PR TITLE
Run notebook from scratch

### PR DESCRIPTION
**Pull request by afestein**
To ensure we get a clean final submission, I've run the entire notebook
from the top, which will fetch new tweets and generate the JSON files.

I also generated the .html file which also needs to be submitted.

### CODE REVIEW

**Comment by afestein** [comment]
If anyone wants to run the entire notebook and see if they get better looking distribution on the graphs then please feel free @jjjjesse @willem-h

**Comment by afestein** [comment]
The html output is also an easy way for each of us to do our 'final review' of the code.

**Comment by willem-h** [comment]
screen shot 2017-09-09 at 9 01 04 am
screen shot 2017-09-09 at 9 01 29 am
screen shot 2017-09-09 at 9 01 34 am

**Review by willem-h — APPROVED** [review]
:shipit:

**Pull request merged**
