### PR TITLE
Print first 1000 tweet cluster labels (2.18)

### LINKED ISSUE #34: 2.18

### PR DESCRIPTION
**Pull request by willem-h**
Closes #34.

### CODE REVIEW

**Comment by willem-h** [comment]
Ready for review @afestein @jjjjesse.

**Comment by willem-h** [comment]
[SIT112 Group Problem Solving Task (Week 5)](https://trello.com/c/b6PhVLef/182-sit112-group-problem-solving-task-week-5)

**Comment by jjjjesse** [comment]
Changed formatting so it prints horizontally rather than vertically. 
Also it didn't seem to print 1000, what did you guys get?

**Comment by willem-h** [comment]
Good idea to do it horizontally 👍 

When I was testing it I made sure it printed 1000 by also including the index in what was printed out. I'm not sure why you wouldn't be getting 1000. Did you try a different solution to see if you could get 1000? Maybe the tweets hadn't been imported fully when you ran it?

**Comment by afestein** [comment]
I see 1000 in my result.

**Review by afestein — APPROVED** [review]
Maybe try running it again from the top @jjjjesse?

**Pull request merged**
