### PR TITLE
Calculate distance between all tweets (2.15)

### LINKED ISSUE #31: 2.15

### PR DESCRIPTION
**Pull request by willem-h**
Calculating the pairwise distance between each tweet is needed for the
k-means clustering to find the distinct groups within the data.

A visualisation of these distances is also included to clarify exactly what
is going on in a human readable way.

Closes #31.

### CODE REVIEW

**Comment by willem-h** [comment]
It would be good to get this reviewed but I've based it off #40 so there's potential it could screw up if not merged in order or there are other changes. Just a heads up.

**Comment by willem-h** [comment]
I don't think it would break anything too bad if we merged these out of order (we're not running any production applications) but just to keep things as shippable as possible it would be cool if we could keep the merge order sequential too.

You've probably already thought about this - just a heads up.

**Comment by willem-h** [comment]
[SIT112 Group Problem Solving Task (Week 5)](https://trello.com/c/b6PhVLef/182-sit112-group-problem-solving-task-week-5)

**Comment by willem-h** [comment]
👀 please @afestein @jjjjesse

**Review by jjjjesse — APPROVED** [review]
Looks great

**Pull request merged**
