### PR TITLE
Run the whole document for comparison

### PR DESCRIPTION
**Pull request by willem-h**
This is a PR to compare against as the distribution graphs (the last 3
questions) will change depending on what tweets were collected.

### CODE REVIEW

**Comment by willem-h** [comment]
screen shot 2017-09-09 at 8 58 42 am
screen shot 2017-09-09 at 8 58 52 am
screen shot 2017-09-09 at 8 58 58 am

**Comment by willem-h** [comment]
Just another one to compare with #47 @afestein @jjjjesse

**Comment by afestein** [comment]
Cool. I don't have a strong feeling about how the graphs should look (higher distribution to one keyword means the script did a better job at clustering though, right?)

**Comment by willem-h** [comment]
Something like that. It's only an aesthetic difference that doesn't impact on anything else.

I'm happy with where we're at to submit anything.

**Comment by jjjjesse** [comment]
I think what it comes down to is that everything's functioning as it should be

**Comment by jjjjesse** [comment]
Do we all have to upload btw? Or is it just one?

**Comment by willem-h** [comment]
I'm not sure about the submission. I'll chuck a question on the discussion board.

**Comment by afestein** [comment]
I think I saw someone else ask the same thing, pretty sure only one member has to submit. Be good to confirm though.

**Comment by willem-h** [comment]
Yep, just one person needs to submit 👍

**Pull request closed without merging**
